package by.matmux.controller.command;

public enum CommandNameArray {
    ADDITION_ARR, BINARY_SEARCH, FIBONACHI, FIND_BY_VALUE, FIND_MAX,
    FIND_MIN, FIND_PRIME, FIND_THREE_DIGITS, MULTIPLICATION, QUICK_SORT_ARR, SET_ARR_RANDOM,
    SET_ARR_FILES, SHELL_SORT, SHUTTLE_SORT, SORT_MAX_IN_ROW, SORT_MIN_IN_ROW,
    SORT_SUM_ROW, TRANSPOSITION, SUBTRACTION, CHECK_SQUARE;
}
