package by.matmux.controller.command;

public enum CommandName {
    ADD_BOOK, ADD_JOURNAL, ADD_ALBUM, REMOVE_BOOK, REMOVE_JOURNAL, REMOVE_ALBUM, UPDATE_EDITION, FIND_EDITION_BY_TITLE,
    FIND_EDITION_BY_AUTHORS, FIND_EDITION_BY_NUMBER_PAGES, FIND_EDITION_BY_DATE, FIND_EDITION_BY_PUBLISHING_HOUSE,
    FIND_EDITION_BEFORE_DATE, FIND_EDITION_BY_ID, FIND_EDITION_INTERVAL_ID, FIND_EDITION_BY_TYPE,
    SORT_EDITION_BY_TITLE, SORT_EDITION_BY_AUTHORS, SORT_EDITION_BY_DATE, SORT_EDITION_BY_NUMBER_PAGES,
    SORT_EDITION_BY_PUBLISHING_HOUSE, SORT_BOOK_BY_NUMBER_PAGES, SORT_ALBUM_BY_TITLE, SORT_JOURNAL_BY_AUTHORS,
    SET_EDITION_FROM_FILES, WRONG_REQ;
}
