package by.matmux.controller.command;

public enum CommandName {
    ADD_BOOK, REMOVE_BOOK, FIND_BOOK_BY_TITLE, FIND_BOOK_BY_AUTHORS, FIND_BOOK_BY_NUMBER_PAGES,
    FIND_BOOK_BY_DATE, FIND_BOOK_BY_PUBLISHING_HOUSE, SORT_BOOK_BY_TITLE, SORT_BOOK_BY_AUTHORS,
    SORT_BOOK_BY_DATE, SORT_BOOK_BY_NUMBER_PAGES, SORT_BOOK_BY_PUBLISHING_HOUSE, SET_BOOK_FROM_FILES, WRONG_REQ;
}
